spring:
  datasource:
    url: jdbc:mysql://192.168.0.113/fileupload?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
    continue-on-error: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    title: FileUpload
  thymeleaf:
    cache: false

  http:
    multipart:
      max-file-size: 1Mb
    
file:
  directory: /Users/brunoeverton/Documents/tmp/